# Header
menu:
  主页: /
  随笔: /categories/Suibi
  ios: /categories/iOS
  

# SubNav
subnav:
  github: "https://github.com/lfsluoye"
  weibo: "http://weibo.com/2632170711"
  rss: /atom.xml
  # facebook: "/"
  # google: "/"
  # twitter: "/"
  # linkedin: "/"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

avatar: /assets/blogImg/lfsluoye.png

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: "litten-hexo"

smart_menu:
  innerArchive: '所有文章'
  tagcloud: '标签'
  friends: false
  aboutme: '关于我'

friends:
  友情链接1: http://localhost:4000/
  友情链接2: http://localhost:4000/
  友情链接3: http://localhost:4000/
  友情链接4: http://localhost:4000/
  友情链接5: http://localhost:4000/
  友情链接6: http://localhost:4000/
  
aboutme: 李甫帅 <br>14年开始从事ios开发<br/>目前就职于北京建科研软件有限公司.